// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: destination_rule.proto

package io.ourea.adapter.model.istio;

public interface ConnectionPoolSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:istio.networking.v1alpha3.ConnectionPoolSettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Settings common to both HTTP and TCP upstream connections.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.ConnectionPoolSettings.TCPSettings tcp = 1;</code>
   * @return Whether the tcp field is set.
   */
  boolean hasTcp();
  /**
   * <pre>
   * Settings common to both HTTP and TCP upstream connections.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.ConnectionPoolSettings.TCPSettings tcp = 1;</code>
   * @return The tcp.
   */
  io.ourea.adapter.model.istio.ConnectionPoolSettings.TCPSettings getTcp();
  /**
   * <pre>
   * Settings common to both HTTP and TCP upstream connections.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.ConnectionPoolSettings.TCPSettings tcp = 1;</code>
   */
  io.ourea.adapter.model.istio.ConnectionPoolSettings.TCPSettingsOrBuilder getTcpOrBuilder();

  /**
   * <pre>
   * HTTP connection pool settings.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.ConnectionPoolSettings.HTTPSettings http = 2;</code>
   * @return Whether the http field is set.
   */
  boolean hasHttp();
  /**
   * <pre>
   * HTTP connection pool settings.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.ConnectionPoolSettings.HTTPSettings http = 2;</code>
   * @return The http.
   */
  io.ourea.adapter.model.istio.ConnectionPoolSettings.HTTPSettings getHttp();
  /**
   * <pre>
   * HTTP connection pool settings.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.ConnectionPoolSettings.HTTPSettings http = 2;</code>
   */
  io.ourea.adapter.model.istio.ConnectionPoolSettings.HTTPSettingsOrBuilder getHttpOrBuilder();
}
