// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: destination_rule.proto

package io.ourea.adapter.model.istio;

public final class DestinationRuleOuterClass {
  private DestinationRuleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_DestinationRule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_DestinationRule_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_TrafficPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_TrafficPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_TrafficPolicy_PortTrafficPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_TrafficPolicy_PortTrafficPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_Subset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_Subset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_Subset_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_Subset_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_LoadBalancerSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_LoadBalancerSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_HTTPCookie_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_HTTPCookie_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_TcpKeepalive_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_TcpKeepalive_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_HTTPSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_HTTPSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_OutlierDetection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_OutlierDetection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_ClientTLSSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_ClientTLSSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_ToEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_ToEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Failover_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Failover_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026destination_rule.proto\022\031istio.networki" +
      "ng.v1alpha3\032\024field_behavior.proto\032\036googl" +
      "e/protobuf/duration.proto\032\036google/protob" +
      "uf/wrappers.proto\032\025virtual_service.proto" +
      "\"\255\001\n\017DestinationRule\022\021\n\004host\030\001 \001(\tB\003\340A\002\022" +
      "@\n\016traffic_policy\030\002 \001(\0132(.istio.networki" +
      "ng.v1alpha3.TrafficPolicy\0222\n\007subsets\030\003 \003" +
      "(\0132!.istio.networking.v1alpha3.Subset\022\021\n" +
      "\texport_to\030\004 \003(\t\"\343\005\n\rTrafficPolicy\022F\n\rlo" +
      "ad_balancer\030\001 \001(\0132/.istio.networking.v1a" +
      "lpha3.LoadBalancerSettings\022J\n\017connection" +
      "_pool\030\002 \001(\01321.istio.networking.v1alpha3." +
      "ConnectionPoolSettings\022F\n\021outlier_detect" +
      "ion\030\003 \001(\0132+.istio.networking.v1alpha3.Ou" +
      "tlierDetection\0229\n\003tls\030\004 \001(\0132,.istio.netw" +
      "orking.v1alpha3.ClientTLSSettings\022W\n\023por" +
      "t_level_settings\030\005 \003(\0132:.istio.networkin" +
      "g.v1alpha3.TrafficPolicy.PortTrafficPoli" +
      "cy\032\341\002\n\021PortTrafficPolicy\0225\n\004port\030\001 \001(\0132\'" +
      ".istio.networking.v1alpha3.PortSelector\022" +
      "F\n\rload_balancer\030\002 \001(\0132/.istio.networkin" +
      "g.v1alpha3.LoadBalancerSettings\022J\n\017conne" +
      "ction_pool\030\003 \001(\01321.istio.networking.v1al" +
      "pha3.ConnectionPoolSettings\022F\n\021outlier_d" +
      "etection\030\004 \001(\0132+.istio.networking.v1alph" +
      "a3.OutlierDetection\0229\n\003tls\030\005 \001(\0132,.istio" +
      ".networking.v1alpha3.ClientTLSSettings\"\313" +
      "\001\n\006Subset\022\021\n\004name\030\001 \001(\tB\003\340A\002\022=\n\006labels\030\002" +
      " \003(\0132-.istio.networking.v1alpha3.Subset." +
      "LabelsEntry\022@\n\016traffic_policy\030\003 \001(\0132(.is" +
      "tio.networking.v1alpha3.TrafficPolicy\032-\n" +
      "\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"\301\005\n\024LoadBalancerSettings\022J\n\006simple\030" +
      "\001 \001(\01628.istio.networking.v1alpha3.LoadBa" +
      "lancerSettings.SimpleLBH\000\022[\n\017consistent_" +
      "hash\030\002 \001(\0132@.istio.networking.v1alpha3.L" +
      "oadBalancerSettings.ConsistentHashLBH\000\022S" +
      "\n\023locality_lb_setting\030\003 \001(\01326.istio.netw" +
      "orking.v1alpha3.LocalityLoadBalancerSett" +
      "ing\032\323\002\n\020ConsistentHashLB\022\032\n\020http_header_" +
      "name\030\001 \001(\tH\000\022b\n\013http_cookie\030\002 \001(\0132K.isti" +
      "o.networking.v1alpha3.LoadBalancerSettin" +
      "gs.ConsistentHashLB.HTTPCookieH\000\022\027\n\ruse_" +
      "source_ip\030\003 \001(\010H\000\022#\n\031http_query_paramete" +
      "r_name\030\005 \001(\tH\000\022\031\n\021minimum_ring_size\030\004 \001(" +
      "\004\032Z\n\nHTTPCookie\022\021\n\004name\030\001 \001(\tB\003\340A\002\022\014\n\004pa" +
      "th\030\002 \001(\t\022+\n\003ttl\030\003 \001(\0132\031.google.protobuf." +
      "DurationB\003\340A\002B\n\n\010hash_key\"H\n\010SimpleLB\022\017\n" +
      "\013ROUND_ROBIN\020\000\022\016\n\nLEAST_CONN\020\001\022\n\n\006RANDOM" +
      "\020\002\022\017\n\013PASSTHROUGH\020\003B\013\n\tlb_policy\"\320\006\n\026Con" +
      "nectionPoolSettings\022J\n\003tcp\030\001 \001(\0132=.istio" +
      ".networking.v1alpha3.ConnectionPoolSetti" +
      "ngs.TCPSettings\022L\n\004http\030\002 \001(\0132>.istio.ne" +
      "tworking.v1alpha3.ConnectionPoolSettings" +
      ".HTTPSettings\032\263\002\n\013TCPSettings\022\027\n\017max_con" +
      "nections\030\001 \001(\005\0222\n\017connect_timeout\030\002 \001(\0132" +
      "\031.google.protobuf.Duration\022a\n\rtcp_keepal" +
      "ive\030\003 \001(\0132J.istio.networking.v1alpha3.Co" +
      "nnectionPoolSettings.TCPSettings.TcpKeep" +
      "alive\032t\n\014TcpKeepalive\022\016\n\006probes\030\001 \001(\r\022\'\n" +
      "\004time\030\002 \001(\0132\031.google.protobuf.Duration\022+" +
      "\n\010interval\030\003 \001(\0132\031.google.protobuf.Durat" +
      "ion\032\345\002\n\014HTTPSettings\022\"\n\032http1_max_pendin" +
      "g_requests\030\001 \001(\005\022\032\n\022http2_max_requests\030\002" +
      " \001(\005\022#\n\033max_requests_per_connection\030\003 \001(" +
      "\005\022\023\n\013max_retries\030\004 \001(\005\022/\n\014idle_timeout\030\005" +
      " \001(\0132\031.google.protobuf.Duration\022i\n\021h2_up" +
      "grade_policy\030\006 \001(\0162N.istio.networking.v1" +
      "alpha3.ConnectionPoolSettings.HTTPSettin" +
      "gs.H2UpgradePolicy\"?\n\017H2UpgradePolicy\022\013\n" +
      "\007DEFAULT\020\000\022\022\n\016DO_NOT_UPGRADE\020\001\022\013\n\007UPGRAD" +
      "E\020\002\"\320\002\n\020OutlierDetection\022\036\n\022consecutive_" +
      "errors\030\001 \001(\005B\002\030\001\022@\n\032consecutive_gateway_" +
      "errors\030\006 \001(\0132\034.google.protobuf.UInt32Val" +
      "ue\022<\n\026consecutive_5xx_errors\030\007 \001(\0132\034.goo" +
      "gle.protobuf.UInt32Value\022+\n\010interval\030\002 \001" +
      "(\0132\031.google.protobuf.Duration\0225\n\022base_ej" +
      "ection_time\030\003 \001(\0132\031.google.protobuf.Dura" +
      "tion\022\034\n\024max_ejection_percent\030\004 \001(\005\022\032\n\022mi" +
      "n_health_percent\030\005 \001(\005\"\251\002\n\021ClientTLSSett" +
      "ings\022G\n\004mode\030\001 \001(\01624.istio.networking.v1" +
      "alpha3.ClientTLSSettings.TLSmodeB\003\340A\002\022\032\n" +
      "\022client_certificate\030\002 \001(\t\022\023\n\013private_key" +
      "\030\003 \001(\t\022\027\n\017ca_certificates\030\004 \001(\t\022\027\n\017crede" +
      "ntial_name\030\007 \001(\t\022\031\n\021subject_alt_names\030\005 " +
      "\003(\t\022\013\n\003sni\030\006 \001(\t\"@\n\007TLSmode\022\013\n\007DISABLE\020\000" +
      "\022\n\n\006SIMPLE\020\001\022\n\n\006MUTUAL\020\002\022\020\n\014ISTIO_MUTUAL" +
      "\020\003\"\271\003\n\033LocalityLoadBalancerSetting\022U\n\ndi" +
      "stribute\030\001 \003(\0132A.istio.networking.v1alph" +
      "a3.LocalityLoadBalancerSetting.Distribut" +
      "e\022Q\n\010failover\030\002 \003(\0132?.istio.networking.v" +
      "1alpha3.LocalityLoadBalancerSetting.Fail" +
      "over\022+\n\007enabled\030\003 \001(\0132\032.google.protobuf." +
      "BoolValue\032\234\001\n\nDistribute\022\014\n\004from\030\001 \001(\t\022U" +
      "\n\002to\030\002 \003(\0132I.istio.networking.v1alpha3.L" +
      "ocalityLoadBalancerSetting.Distribute.To" +
      "Entry\032)\n\007ToEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\r:\0028\001\032$\n\010Failover\022\014\n\004from\030\001 \001(\t\022\n\n\002to" +
      "\030\002 \001(\tBB\n\034io.ourea.adapter.model.istioP\001" +
      "Z istio.io/api/networking/v1alpha3b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          io.ourea.adapter.model.istio.VirtualServiceOuterClass.getDescriptor(),
        });
    internal_static_istio_networking_v1alpha3_DestinationRule_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_istio_networking_v1alpha3_DestinationRule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_DestinationRule_descriptor,
        new java.lang.String[] { "Host", "TrafficPolicy", "Subsets", "ExportTo", });
    internal_static_istio_networking_v1alpha3_TrafficPolicy_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_istio_networking_v1alpha3_TrafficPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_TrafficPolicy_descriptor,
        new java.lang.String[] { "LoadBalancer", "ConnectionPool", "OutlierDetection", "Tls", "PortLevelSettings", });
    internal_static_istio_networking_v1alpha3_TrafficPolicy_PortTrafficPolicy_descriptor =
      internal_static_istio_networking_v1alpha3_TrafficPolicy_descriptor.getNestedTypes().get(0);
    internal_static_istio_networking_v1alpha3_TrafficPolicy_PortTrafficPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_TrafficPolicy_PortTrafficPolicy_descriptor,
        new java.lang.String[] { "Port", "LoadBalancer", "ConnectionPool", "OutlierDetection", "Tls", });
    internal_static_istio_networking_v1alpha3_Subset_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_istio_networking_v1alpha3_Subset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_Subset_descriptor,
        new java.lang.String[] { "Name", "Labels", "TrafficPolicy", });
    internal_static_istio_networking_v1alpha3_Subset_LabelsEntry_descriptor =
      internal_static_istio_networking_v1alpha3_Subset_descriptor.getNestedTypes().get(0);
    internal_static_istio_networking_v1alpha3_Subset_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_Subset_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_istio_networking_v1alpha3_LoadBalancerSettings_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_istio_networking_v1alpha3_LoadBalancerSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_LoadBalancerSettings_descriptor,
        new java.lang.String[] { "Simple", "ConsistentHash", "LocalityLbSetting", "LbPolicy", });
    internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_descriptor =
      internal_static_istio_networking_v1alpha3_LoadBalancerSettings_descriptor.getNestedTypes().get(0);
    internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_descriptor,
        new java.lang.String[] { "HttpHeaderName", "HttpCookie", "UseSourceIp", "HttpQueryParameterName", "MinimumRingSize", "HashKey", });
    internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_HTTPCookie_descriptor =
      internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_descriptor.getNestedTypes().get(0);
    internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_HTTPCookie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_LoadBalancerSettings_ConsistentHashLB_HTTPCookie_descriptor,
        new java.lang.String[] { "Name", "Path", "Ttl", });
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_descriptor,
        new java.lang.String[] { "Tcp", "Http", });
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_descriptor =
      internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_descriptor.getNestedTypes().get(0);
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_descriptor,
        new java.lang.String[] { "MaxConnections", "ConnectTimeout", "TcpKeepalive", });
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_TcpKeepalive_descriptor =
      internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_descriptor.getNestedTypes().get(0);
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_TcpKeepalive_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_TCPSettings_TcpKeepalive_descriptor,
        new java.lang.String[] { "Probes", "Time", "Interval", });
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_HTTPSettings_descriptor =
      internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_descriptor.getNestedTypes().get(1);
    internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_HTTPSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_ConnectionPoolSettings_HTTPSettings_descriptor,
        new java.lang.String[] { "Http1MaxPendingRequests", "Http2MaxRequests", "MaxRequestsPerConnection", "MaxRetries", "IdleTimeout", "H2UpgradePolicy", });
    internal_static_istio_networking_v1alpha3_OutlierDetection_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_istio_networking_v1alpha3_OutlierDetection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_OutlierDetection_descriptor,
        new java.lang.String[] { "ConsecutiveErrors", "ConsecutiveGatewayErrors", "Consecutive5XxErrors", "Interval", "BaseEjectionTime", "MaxEjectionPercent", "MinHealthPercent", });
    internal_static_istio_networking_v1alpha3_ClientTLSSettings_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_istio_networking_v1alpha3_ClientTLSSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_ClientTLSSettings_descriptor,
        new java.lang.String[] { "Mode", "ClientCertificate", "PrivateKey", "CaCertificates", "CredentialName", "SubjectAltNames", "Sni", });
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_descriptor,
        new java.lang.String[] { "Distribute", "Failover", "Enabled", });
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_descriptor =
      internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_descriptor.getNestedTypes().get(0);
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_descriptor,
        new java.lang.String[] { "From", "To", });
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_ToEntry_descriptor =
      internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_descriptor.getNestedTypes().get(0);
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_ToEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Distribute_ToEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Failover_descriptor =
      internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_descriptor.getNestedTypes().get(1);
    internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Failover_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_networking_v1alpha3_LocalityLoadBalancerSetting_Failover_descriptor,
        new java.lang.String[] { "From", "To", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    io.ourea.adapter.model.istio.VirtualServiceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
