// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: virtual_service.proto

package io.ourea.adapter.model.istio;

public interface DestinationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:istio.networking.v1alpha3.Destination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of a service from the service registry. Service
   * names are looked up from the platform's service registry (e.g.,
   * Kubernetes services, Consul services, etc.) and from the hosts
   * declared by [ServiceEntry](https://istio.io/docs/reference/config/networking/service-entry/#ServiceEntry). Traffic forwarded to
   * destinations that are not found in either of the two, will be dropped.
   * *Note for Kubernetes users*: When short names are used (e.g. "reviews"
   * instead of "reviews.default.svc.cluster.local"), Istio will interpret
   * the short name based on the namespace of the rule, not the service. A
   * rule in the "default" namespace containing a host "reviews will be
   * interpreted as "reviews.default.svc.cluster.local", irrespective of
   * the actual namespace associated with the reviews service. To avoid
   * potential misconfiguration, it is recommended to always use fully
   * qualified domain names over short names.
   * </pre>
   *
   * <code>string host = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The host.
   */
  java.lang.String getHost();
  /**
   * <pre>
   * The name of a service from the service registry. Service
   * names are looked up from the platform's service registry (e.g.,
   * Kubernetes services, Consul services, etc.) and from the hosts
   * declared by [ServiceEntry](https://istio.io/docs/reference/config/networking/service-entry/#ServiceEntry). Traffic forwarded to
   * destinations that are not found in either of the two, will be dropped.
   * *Note for Kubernetes users*: When short names are used (e.g. "reviews"
   * instead of "reviews.default.svc.cluster.local"), Istio will interpret
   * the short name based on the namespace of the rule, not the service. A
   * rule in the "default" namespace containing a host "reviews will be
   * interpreted as "reviews.default.svc.cluster.local", irrespective of
   * the actual namespace associated with the reviews service. To avoid
   * potential misconfiguration, it is recommended to always use fully
   * qualified domain names over short names.
   * </pre>
   *
   * <code>string host = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <pre>
   * The name of a subset within the service. Applicable only to services
   * within the mesh. The subset must be defined in a corresponding
   * DestinationRule.
   * </pre>
   *
   * <code>string subset = 2;</code>
   * @return The subset.
   */
  java.lang.String getSubset();
  /**
   * <pre>
   * The name of a subset within the service. Applicable only to services
   * within the mesh. The subset must be defined in a corresponding
   * DestinationRule.
   * </pre>
   *
   * <code>string subset = 2;</code>
   * @return The bytes for subset.
   */
  com.google.protobuf.ByteString
      getSubsetBytes();

  /**
   * <pre>
   * Specifies the port on the host that is being addressed. If a service
   * exposes only a single port it is not required to explicitly select the
   * port.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.PortSelector port = 3;</code>
   * @return Whether the port field is set.
   */
  boolean hasPort();
  /**
   * <pre>
   * Specifies the port on the host that is being addressed. If a service
   * exposes only a single port it is not required to explicitly select the
   * port.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.PortSelector port = 3;</code>
   * @return The port.
   */
  io.ourea.adapter.model.istio.PortSelector getPort();
  /**
   * <pre>
   * Specifies the port on the host that is being addressed. If a service
   * exposes only a single port it is not required to explicitly select the
   * port.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.PortSelector port = 3;</code>
   */
  io.ourea.adapter.model.istio.PortSelectorOrBuilder getPortOrBuilder();
}
