// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: virtual_service.proto

package io.ourea.adapter.model.istio;

public interface HeadersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:istio.networking.v1alpha3.Headers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Header manipulation rules to apply before forwarding a request
   * to the destination service
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Headers.HeaderOperations request = 1;</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <pre>
   * Header manipulation rules to apply before forwarding a request
   * to the destination service
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Headers.HeaderOperations request = 1;</code>
   * @return The request.
   */
  io.ourea.adapter.model.istio.Headers.HeaderOperations getRequest();
  /**
   * <pre>
   * Header manipulation rules to apply before forwarding a request
   * to the destination service
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Headers.HeaderOperations request = 1;</code>
   */
  io.ourea.adapter.model.istio.Headers.HeaderOperationsOrBuilder getRequestOrBuilder();

  /**
   * <pre>
   * Header manipulation rules to apply before returning a response
   * to the caller
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Headers.HeaderOperations response = 2;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <pre>
   * Header manipulation rules to apply before returning a response
   * to the caller
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Headers.HeaderOperations response = 2;</code>
   * @return The response.
   */
  io.ourea.adapter.model.istio.Headers.HeaderOperations getResponse();
  /**
   * <pre>
   * Header manipulation rules to apply before returning a response
   * to the caller
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Headers.HeaderOperations response = 2;</code>
   */
  io.ourea.adapter.model.istio.Headers.HeaderOperationsOrBuilder getResponseOrBuilder();
}
