// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: virtual_service.proto

package io.ourea.adapter.model.istio;

public interface HTTPRewriteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:istio.networking.v1alpha3.HTTPRewrite)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * rewrite the path (or the prefix) portion of the URI with this
   * value. If the original URI was matched based on prefix, the value
   * provided in this field will replace the corresponding matched prefix.
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <pre>
   * rewrite the path (or the prefix) portion of the URI with this
   * value. If the original URI was matched based on prefix, the value
   * provided in this field will replace the corresponding matched prefix.
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();

  /**
   * <pre>
   * rewrite the Authority/Host header with this value.
   * </pre>
   *
   * <code>string authority = 2;</code>
   * @return The authority.
   */
  java.lang.String getAuthority();
  /**
   * <pre>
   * rewrite the Authority/Host header with this value.
   * </pre>
   *
   * <code>string authority = 2;</code>
   * @return The bytes for authority.
   */
  com.google.protobuf.ByteString
      getAuthorityBytes();
}
