// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sidecar.proto

package io.ourea.adapter.model.istio;

/**
 * <pre>
 * `IstioIngressListener` specifies the properties of an inbound
 * traffic listener on the sidecar proxy attached to a workload instance.
 * </pre>
 *
 * Protobuf type {@code istio.networking.v1alpha3.IstioIngressListener}
 */
public final class IstioIngressListener extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:istio.networking.v1alpha3.IstioIngressListener)
    IstioIngressListenerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IstioIngressListener.newBuilder() to construct.
  private IstioIngressListener(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IstioIngressListener() {
    bind_ = "";
    captureMode_ = 0;
    defaultEndpoint_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IstioIngressListener();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IstioIngressListener(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.ourea.adapter.model.Port.Builder subBuilder = null;
            if (port_ != null) {
              subBuilder = port_.toBuilder();
            }
            port_ = input.readMessage(io.ourea.adapter.model.Port.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(port_);
              port_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            bind_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            captureMode_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            defaultEndpoint_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ourea.adapter.model.istio.SidecarOuterClass.internal_static_istio_networking_v1alpha3_IstioIngressListener_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ourea.adapter.model.istio.SidecarOuterClass.internal_static_istio_networking_v1alpha3_IstioIngressListener_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ourea.adapter.model.istio.IstioIngressListener.class, io.ourea.adapter.model.istio.IstioIngressListener.Builder.class);
  }

  public static final int PORT_FIELD_NUMBER = 1;
  private io.ourea.adapter.model.Port port_;
  /**
   * <pre>
   * The port associated with the listener.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the port field is set.
   */
  @java.lang.Override
  public boolean hasPort() {
    return port_ != null;
  }
  /**
   * <pre>
   * The port associated with the listener.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The port.
   */
  @java.lang.Override
  public io.ourea.adapter.model.Port getPort() {
    return port_ == null ? io.ourea.adapter.model.Port.getDefaultInstance() : port_;
  }
  /**
   * <pre>
   * The port associated with the listener.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public io.ourea.adapter.model.PortOrBuilder getPortOrBuilder() {
    return getPort();
  }

  public static final int BIND_FIELD_NUMBER = 2;
  private volatile java.lang.Object bind_;
  /**
   * <pre>
   * The IP to which the listener should be bound. Must be in the
   * format `x.x.x.x`. Unix domain socket addresses are not allowed in
   * the bind field for ingress listeners. If omitted, Istio will
   * automatically configure the defaults based on imported services
   * and the workload instances to which this configuration is applied
   * to.
   * </pre>
   *
   * <code>string bind = 2;</code>
   * @return The bind.
   */
  @java.lang.Override
  public java.lang.String getBind() {
    java.lang.Object ref = bind_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bind_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The IP to which the listener should be bound. Must be in the
   * format `x.x.x.x`. Unix domain socket addresses are not allowed in
   * the bind field for ingress listeners. If omitted, Istio will
   * automatically configure the defaults based on imported services
   * and the workload instances to which this configuration is applied
   * to.
   * </pre>
   *
   * <code>string bind = 2;</code>
   * @return The bytes for bind.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBindBytes() {
    java.lang.Object ref = bind_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bind_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAPTURE_MODE_FIELD_NUMBER = 3;
  private int captureMode_;
  /**
   * <pre>
   * The captureMode option dictates how traffic to the listener is
   * expected to be captured (or not).
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.CaptureMode capture_mode = 3;</code>
   * @return The enum numeric value on the wire for captureMode.
   */
  @java.lang.Override public int getCaptureModeValue() {
    return captureMode_;
  }
  /**
   * <pre>
   * The captureMode option dictates how traffic to the listener is
   * expected to be captured (or not).
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.CaptureMode capture_mode = 3;</code>
   * @return The captureMode.
   */
  @java.lang.Override public io.ourea.adapter.model.istio.CaptureMode getCaptureMode() {
    @SuppressWarnings("deprecation")
    io.ourea.adapter.model.istio.CaptureMode result = io.ourea.adapter.model.istio.CaptureMode.valueOf(captureMode_);
    return result == null ? io.ourea.adapter.model.istio.CaptureMode.UNRECOGNIZED : result;
  }

  public static final int DEFAULT_ENDPOINT_FIELD_NUMBER = 4;
  private volatile java.lang.Object defaultEndpoint_;
  /**
   * <pre>
   * The loopback IP endpoint or Unix domain socket to which
   * traffic should be forwarded to. This configuration can be used to
   * redirect traffic arriving at the bind `IP:Port` on the sidecar to a `localhost:port`
   * or Unix domain socket where the application workload instance is listening for
   * connections. Format should be `127.0.0.1:PORT` or `unix:///path/to/socket`
   * </pre>
   *
   * <code>string default_endpoint = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The defaultEndpoint.
   */
  @java.lang.Override
  public java.lang.String getDefaultEndpoint() {
    java.lang.Object ref = defaultEndpoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      defaultEndpoint_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The loopback IP endpoint or Unix domain socket to which
   * traffic should be forwarded to. This configuration can be used to
   * redirect traffic arriving at the bind `IP:Port` on the sidecar to a `localhost:port`
   * or Unix domain socket where the application workload instance is listening for
   * connections. Format should be `127.0.0.1:PORT` or `unix:///path/to/socket`
   * </pre>
   *
   * <code>string default_endpoint = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for defaultEndpoint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDefaultEndpointBytes() {
    java.lang.Object ref = defaultEndpoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      defaultEndpoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (port_ != null) {
      output.writeMessage(1, getPort());
    }
    if (!getBindBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bind_);
    }
    if (captureMode_ != io.ourea.adapter.model.istio.CaptureMode.DEFAULT.getNumber()) {
      output.writeEnum(3, captureMode_);
    }
    if (!getDefaultEndpointBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, defaultEndpoint_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (port_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPort());
    }
    if (!getBindBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bind_);
    }
    if (captureMode_ != io.ourea.adapter.model.istio.CaptureMode.DEFAULT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, captureMode_);
    }
    if (!getDefaultEndpointBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, defaultEndpoint_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ourea.adapter.model.istio.IstioIngressListener)) {
      return super.equals(obj);
    }
    io.ourea.adapter.model.istio.IstioIngressListener other = (io.ourea.adapter.model.istio.IstioIngressListener) obj;

    if (hasPort() != other.hasPort()) return false;
    if (hasPort()) {
      if (!getPort()
          .equals(other.getPort())) return false;
    }
    if (!getBind()
        .equals(other.getBind())) return false;
    if (captureMode_ != other.captureMode_) return false;
    if (!getDefaultEndpoint()
        .equals(other.getDefaultEndpoint())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPort()) {
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort().hashCode();
    }
    hash = (37 * hash) + BIND_FIELD_NUMBER;
    hash = (53 * hash) + getBind().hashCode();
    hash = (37 * hash) + CAPTURE_MODE_FIELD_NUMBER;
    hash = (53 * hash) + captureMode_;
    hash = (37 * hash) + DEFAULT_ENDPOINT_FIELD_NUMBER;
    hash = (53 * hash) + getDefaultEndpoint().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ourea.adapter.model.istio.IstioIngressListener parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ourea.adapter.model.istio.IstioIngressListener parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ourea.adapter.model.istio.IstioIngressListener prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * `IstioIngressListener` specifies the properties of an inbound
   * traffic listener on the sidecar proxy attached to a workload instance.
   * </pre>
   *
   * Protobuf type {@code istio.networking.v1alpha3.IstioIngressListener}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:istio.networking.v1alpha3.IstioIngressListener)
      io.ourea.adapter.model.istio.IstioIngressListenerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ourea.adapter.model.istio.SidecarOuterClass.internal_static_istio_networking_v1alpha3_IstioIngressListener_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ourea.adapter.model.istio.SidecarOuterClass.internal_static_istio_networking_v1alpha3_IstioIngressListener_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ourea.adapter.model.istio.IstioIngressListener.class, io.ourea.adapter.model.istio.IstioIngressListener.Builder.class);
    }

    // Construct using io.ourea.adapter.model.istio.IstioIngressListener.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (portBuilder_ == null) {
        port_ = null;
      } else {
        port_ = null;
        portBuilder_ = null;
      }
      bind_ = "";

      captureMode_ = 0;

      defaultEndpoint_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ourea.adapter.model.istio.SidecarOuterClass.internal_static_istio_networking_v1alpha3_IstioIngressListener_descriptor;
    }

    @java.lang.Override
    public io.ourea.adapter.model.istio.IstioIngressListener getDefaultInstanceForType() {
      return io.ourea.adapter.model.istio.IstioIngressListener.getDefaultInstance();
    }

    @java.lang.Override
    public io.ourea.adapter.model.istio.IstioIngressListener build() {
      io.ourea.adapter.model.istio.IstioIngressListener result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ourea.adapter.model.istio.IstioIngressListener buildPartial() {
      io.ourea.adapter.model.istio.IstioIngressListener result = new io.ourea.adapter.model.istio.IstioIngressListener(this);
      if (portBuilder_ == null) {
        result.port_ = port_;
      } else {
        result.port_ = portBuilder_.build();
      }
      result.bind_ = bind_;
      result.captureMode_ = captureMode_;
      result.defaultEndpoint_ = defaultEndpoint_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ourea.adapter.model.istio.IstioIngressListener) {
        return mergeFrom((io.ourea.adapter.model.istio.IstioIngressListener)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ourea.adapter.model.istio.IstioIngressListener other) {
      if (other == io.ourea.adapter.model.istio.IstioIngressListener.getDefaultInstance()) return this;
      if (other.hasPort()) {
        mergePort(other.getPort());
      }
      if (!other.getBind().isEmpty()) {
        bind_ = other.bind_;
        onChanged();
      }
      if (other.captureMode_ != 0) {
        setCaptureModeValue(other.getCaptureModeValue());
      }
      if (!other.getDefaultEndpoint().isEmpty()) {
        defaultEndpoint_ = other.defaultEndpoint_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.ourea.adapter.model.istio.IstioIngressListener parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.ourea.adapter.model.istio.IstioIngressListener) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.ourea.adapter.model.Port port_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ourea.adapter.model.Port, io.ourea.adapter.model.Port.Builder, io.ourea.adapter.model.PortOrBuilder> portBuilder_;
    /**
     * <pre>
     * The port associated with the listener.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the port field is set.
     */
    public boolean hasPort() {
      return portBuilder_ != null || port_ != null;
    }
    /**
     * <pre>
     * The port associated with the listener.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The port.
     */
    public io.ourea.adapter.model.Port getPort() {
      if (portBuilder_ == null) {
        return port_ == null ? io.ourea.adapter.model.Port.getDefaultInstance() : port_;
      } else {
        return portBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The port associated with the listener.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setPort(io.ourea.adapter.model.Port value) {
      if (portBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        port_ = value;
        onChanged();
      } else {
        portBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The port associated with the listener.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setPort(
        io.ourea.adapter.model.Port.Builder builderForValue) {
      if (portBuilder_ == null) {
        port_ = builderForValue.build();
        onChanged();
      } else {
        portBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The port associated with the listener.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergePort(io.ourea.adapter.model.Port value) {
      if (portBuilder_ == null) {
        if (port_ != null) {
          port_ =
            io.ourea.adapter.model.Port.newBuilder(port_).mergeFrom(value).buildPartial();
        } else {
          port_ = value;
        }
        onChanged();
      } else {
        portBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The port associated with the listener.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearPort() {
      if (portBuilder_ == null) {
        port_ = null;
        onChanged();
      } else {
        port_ = null;
        portBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The port associated with the listener.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.ourea.adapter.model.Port.Builder getPortBuilder() {
      
      onChanged();
      return getPortFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The port associated with the listener.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.ourea.adapter.model.PortOrBuilder getPortOrBuilder() {
      if (portBuilder_ != null) {
        return portBuilder_.getMessageOrBuilder();
      } else {
        return port_ == null ?
            io.ourea.adapter.model.Port.getDefaultInstance() : port_;
      }
    }
    /**
     * <pre>
     * The port associated with the listener.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Port port = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ourea.adapter.model.Port, io.ourea.adapter.model.Port.Builder, io.ourea.adapter.model.PortOrBuilder> 
        getPortFieldBuilder() {
      if (portBuilder_ == null) {
        portBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ourea.adapter.model.Port, io.ourea.adapter.model.Port.Builder, io.ourea.adapter.model.PortOrBuilder>(
                getPort(),
                getParentForChildren(),
                isClean());
        port_ = null;
      }
      return portBuilder_;
    }

    private java.lang.Object bind_ = "";
    /**
     * <pre>
     * The IP to which the listener should be bound. Must be in the
     * format `x.x.x.x`. Unix domain socket addresses are not allowed in
     * the bind field for ingress listeners. If omitted, Istio will
     * automatically configure the defaults based on imported services
     * and the workload instances to which this configuration is applied
     * to.
     * </pre>
     *
     * <code>string bind = 2;</code>
     * @return The bind.
     */
    public java.lang.String getBind() {
      java.lang.Object ref = bind_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bind_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The IP to which the listener should be bound. Must be in the
     * format `x.x.x.x`. Unix domain socket addresses are not allowed in
     * the bind field for ingress listeners. If omitted, Istio will
     * automatically configure the defaults based on imported services
     * and the workload instances to which this configuration is applied
     * to.
     * </pre>
     *
     * <code>string bind = 2;</code>
     * @return The bytes for bind.
     */
    public com.google.protobuf.ByteString
        getBindBytes() {
      java.lang.Object ref = bind_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The IP to which the listener should be bound. Must be in the
     * format `x.x.x.x`. Unix domain socket addresses are not allowed in
     * the bind field for ingress listeners. If omitted, Istio will
     * automatically configure the defaults based on imported services
     * and the workload instances to which this configuration is applied
     * to.
     * </pre>
     *
     * <code>string bind = 2;</code>
     * @param value The bind to set.
     * @return This builder for chaining.
     */
    public Builder setBind(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The IP to which the listener should be bound. Must be in the
     * format `x.x.x.x`. Unix domain socket addresses are not allowed in
     * the bind field for ingress listeners. If omitted, Istio will
     * automatically configure the defaults based on imported services
     * and the workload instances to which this configuration is applied
     * to.
     * </pre>
     *
     * <code>string bind = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBind() {
      
      bind_ = getDefaultInstance().getBind();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The IP to which the listener should be bound. Must be in the
     * format `x.x.x.x`. Unix domain socket addresses are not allowed in
     * the bind field for ingress listeners. If omitted, Istio will
     * automatically configure the defaults based on imported services
     * and the workload instances to which this configuration is applied
     * to.
     * </pre>
     *
     * <code>string bind = 2;</code>
     * @param value The bytes for bind to set.
     * @return This builder for chaining.
     */
    public Builder setBindBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bind_ = value;
      onChanged();
      return this;
    }

    private int captureMode_ = 0;
    /**
     * <pre>
     * The captureMode option dictates how traffic to the listener is
     * expected to be captured (or not).
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.CaptureMode capture_mode = 3;</code>
     * @return The enum numeric value on the wire for captureMode.
     */
    @java.lang.Override public int getCaptureModeValue() {
      return captureMode_;
    }
    /**
     * <pre>
     * The captureMode option dictates how traffic to the listener is
     * expected to be captured (or not).
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.CaptureMode capture_mode = 3;</code>
     * @param value The enum numeric value on the wire for captureMode to set.
     * @return This builder for chaining.
     */
    public Builder setCaptureModeValue(int value) {
      
      captureMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The captureMode option dictates how traffic to the listener is
     * expected to be captured (or not).
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.CaptureMode capture_mode = 3;</code>
     * @return The captureMode.
     */
    @java.lang.Override
    public io.ourea.adapter.model.istio.CaptureMode getCaptureMode() {
      @SuppressWarnings("deprecation")
      io.ourea.adapter.model.istio.CaptureMode result = io.ourea.adapter.model.istio.CaptureMode.valueOf(captureMode_);
      return result == null ? io.ourea.adapter.model.istio.CaptureMode.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The captureMode option dictates how traffic to the listener is
     * expected to be captured (or not).
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.CaptureMode capture_mode = 3;</code>
     * @param value The captureMode to set.
     * @return This builder for chaining.
     */
    public Builder setCaptureMode(io.ourea.adapter.model.istio.CaptureMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      captureMode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The captureMode option dictates how traffic to the listener is
     * expected to be captured (or not).
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.CaptureMode capture_mode = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCaptureMode() {
      
      captureMode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object defaultEndpoint_ = "";
    /**
     * <pre>
     * The loopback IP endpoint or Unix domain socket to which
     * traffic should be forwarded to. This configuration can be used to
     * redirect traffic arriving at the bind `IP:Port` on the sidecar to a `localhost:port`
     * or Unix domain socket where the application workload instance is listening for
     * connections. Format should be `127.0.0.1:PORT` or `unix:///path/to/socket`
     * </pre>
     *
     * <code>string default_endpoint = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The defaultEndpoint.
     */
    public java.lang.String getDefaultEndpoint() {
      java.lang.Object ref = defaultEndpoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultEndpoint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The loopback IP endpoint or Unix domain socket to which
     * traffic should be forwarded to. This configuration can be used to
     * redirect traffic arriving at the bind `IP:Port` on the sidecar to a `localhost:port`
     * or Unix domain socket where the application workload instance is listening for
     * connections. Format should be `127.0.0.1:PORT` or `unix:///path/to/socket`
     * </pre>
     *
     * <code>string default_endpoint = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for defaultEndpoint.
     */
    public com.google.protobuf.ByteString
        getDefaultEndpointBytes() {
      java.lang.Object ref = defaultEndpoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultEndpoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The loopback IP endpoint or Unix domain socket to which
     * traffic should be forwarded to. This configuration can be used to
     * redirect traffic arriving at the bind `IP:Port` on the sidecar to a `localhost:port`
     * or Unix domain socket where the application workload instance is listening for
     * connections. Format should be `127.0.0.1:PORT` or `unix:///path/to/socket`
     * </pre>
     *
     * <code>string default_endpoint = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The defaultEndpoint to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultEndpoint(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      defaultEndpoint_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The loopback IP endpoint or Unix domain socket to which
     * traffic should be forwarded to. This configuration can be used to
     * redirect traffic arriving at the bind `IP:Port` on the sidecar to a `localhost:port`
     * or Unix domain socket where the application workload instance is listening for
     * connections. Format should be `127.0.0.1:PORT` or `unix:///path/to/socket`
     * </pre>
     *
     * <code>string default_endpoint = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearDefaultEndpoint() {
      
      defaultEndpoint_ = getDefaultInstance().getDefaultEndpoint();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The loopback IP endpoint or Unix domain socket to which
     * traffic should be forwarded to. This configuration can be used to
     * redirect traffic arriving at the bind `IP:Port` on the sidecar to a `localhost:port`
     * or Unix domain socket where the application workload instance is listening for
     * connections. Format should be `127.0.0.1:PORT` or `unix:///path/to/socket`
     * </pre>
     *
     * <code>string default_endpoint = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for defaultEndpoint to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultEndpointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      defaultEndpoint_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:istio.networking.v1alpha3.IstioIngressListener)
  }

  // @@protoc_insertion_point(class_scope:istio.networking.v1alpha3.IstioIngressListener)
  private static final io.ourea.adapter.model.istio.IstioIngressListener DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ourea.adapter.model.istio.IstioIngressListener();
  }

  public static io.ourea.adapter.model.istio.IstioIngressListener getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IstioIngressListener>
      PARSER = new com.google.protobuf.AbstractParser<IstioIngressListener>() {
    @java.lang.Override
    public IstioIngressListener parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IstioIngressListener(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IstioIngressListener> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IstioIngressListener> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ourea.adapter.model.istio.IstioIngressListener getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

