// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: virtual_service.proto

package io.ourea.adapter.model.istio;

/**
 * <pre>
 * L4 routing rule weighted destination.
 * </pre>
 *
 * Protobuf type {@code istio.networking.v1alpha3.RouteDestination}
 */
public final class RouteDestination extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:istio.networking.v1alpha3.RouteDestination)
    RouteDestinationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RouteDestination.newBuilder() to construct.
  private RouteDestination(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RouteDestination() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RouteDestination();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RouteDestination(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.ourea.adapter.model.istio.Destination.Builder subBuilder = null;
            if (destination_ != null) {
              subBuilder = destination_.toBuilder();
            }
            destination_ = input.readMessage(io.ourea.adapter.model.istio.Destination.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(destination_);
              destination_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            weight_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ourea.adapter.model.istio.VirtualServiceOuterClass.internal_static_istio_networking_v1alpha3_RouteDestination_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ourea.adapter.model.istio.VirtualServiceOuterClass.internal_static_istio_networking_v1alpha3_RouteDestination_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ourea.adapter.model.istio.RouteDestination.class, io.ourea.adapter.model.istio.RouteDestination.Builder.class);
  }

  public static final int DESTINATION_FIELD_NUMBER = 1;
  private io.ourea.adapter.model.istio.Destination destination_;
  /**
   * <pre>
   * Destination uniquely identifies the instances of a service
   * to which the request/connection should be forwarded to.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the destination field is set.
   */
  @java.lang.Override
  public boolean hasDestination() {
    return destination_ != null;
  }
  /**
   * <pre>
   * Destination uniquely identifies the instances of a service
   * to which the request/connection should be forwarded to.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The destination.
   */
  @java.lang.Override
  public io.ourea.adapter.model.istio.Destination getDestination() {
    return destination_ == null ? io.ourea.adapter.model.istio.Destination.getDefaultInstance() : destination_;
  }
  /**
   * <pre>
   * Destination uniquely identifies the instances of a service
   * to which the request/connection should be forwarded to.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public io.ourea.adapter.model.istio.DestinationOrBuilder getDestinationOrBuilder() {
    return getDestination();
  }

  public static final int WEIGHT_FIELD_NUMBER = 2;
  private int weight_;
  /**
   * <pre>
   * The proportion of traffic to be forwarded to the service
   * version. If there is only one destination in a rule, all traffic will be
   * routed to it irrespective of the weight.
   * </pre>
   *
   * <code>int32 weight = 2;</code>
   * @return The weight.
   */
  @java.lang.Override
  public int getWeight() {
    return weight_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (destination_ != null) {
      output.writeMessage(1, getDestination());
    }
    if (weight_ != 0) {
      output.writeInt32(2, weight_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (destination_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDestination());
    }
    if (weight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, weight_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ourea.adapter.model.istio.RouteDestination)) {
      return super.equals(obj);
    }
    io.ourea.adapter.model.istio.RouteDestination other = (io.ourea.adapter.model.istio.RouteDestination) obj;

    if (hasDestination() != other.hasDestination()) return false;
    if (hasDestination()) {
      if (!getDestination()
          .equals(other.getDestination())) return false;
    }
    if (getWeight()
        != other.getWeight()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDestination()) {
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + getDestination().hashCode();
    }
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getWeight();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ourea.adapter.model.istio.RouteDestination parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ourea.adapter.model.istio.RouteDestination parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ourea.adapter.model.istio.RouteDestination prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * L4 routing rule weighted destination.
   * </pre>
   *
   * Protobuf type {@code istio.networking.v1alpha3.RouteDestination}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:istio.networking.v1alpha3.RouteDestination)
      io.ourea.adapter.model.istio.RouteDestinationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ourea.adapter.model.istio.VirtualServiceOuterClass.internal_static_istio_networking_v1alpha3_RouteDestination_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ourea.adapter.model.istio.VirtualServiceOuterClass.internal_static_istio_networking_v1alpha3_RouteDestination_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ourea.adapter.model.istio.RouteDestination.class, io.ourea.adapter.model.istio.RouteDestination.Builder.class);
    }

    // Construct using io.ourea.adapter.model.istio.RouteDestination.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (destinationBuilder_ == null) {
        destination_ = null;
      } else {
        destination_ = null;
        destinationBuilder_ = null;
      }
      weight_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ourea.adapter.model.istio.VirtualServiceOuterClass.internal_static_istio_networking_v1alpha3_RouteDestination_descriptor;
    }

    @java.lang.Override
    public io.ourea.adapter.model.istio.RouteDestination getDefaultInstanceForType() {
      return io.ourea.adapter.model.istio.RouteDestination.getDefaultInstance();
    }

    @java.lang.Override
    public io.ourea.adapter.model.istio.RouteDestination build() {
      io.ourea.adapter.model.istio.RouteDestination result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ourea.adapter.model.istio.RouteDestination buildPartial() {
      io.ourea.adapter.model.istio.RouteDestination result = new io.ourea.adapter.model.istio.RouteDestination(this);
      if (destinationBuilder_ == null) {
        result.destination_ = destination_;
      } else {
        result.destination_ = destinationBuilder_.build();
      }
      result.weight_ = weight_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ourea.adapter.model.istio.RouteDestination) {
        return mergeFrom((io.ourea.adapter.model.istio.RouteDestination)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ourea.adapter.model.istio.RouteDestination other) {
      if (other == io.ourea.adapter.model.istio.RouteDestination.getDefaultInstance()) return this;
      if (other.hasDestination()) {
        mergeDestination(other.getDestination());
      }
      if (other.getWeight() != 0) {
        setWeight(other.getWeight());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.ourea.adapter.model.istio.RouteDestination parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.ourea.adapter.model.istio.RouteDestination) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.ourea.adapter.model.istio.Destination destination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ourea.adapter.model.istio.Destination, io.ourea.adapter.model.istio.Destination.Builder, io.ourea.adapter.model.istio.DestinationOrBuilder> destinationBuilder_;
    /**
     * <pre>
     * Destination uniquely identifies the instances of a service
     * to which the request/connection should be forwarded to.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the destination field is set.
     */
    public boolean hasDestination() {
      return destinationBuilder_ != null || destination_ != null;
    }
    /**
     * <pre>
     * Destination uniquely identifies the instances of a service
     * to which the request/connection should be forwarded to.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The destination.
     */
    public io.ourea.adapter.model.istio.Destination getDestination() {
      if (destinationBuilder_ == null) {
        return destination_ == null ? io.ourea.adapter.model.istio.Destination.getDefaultInstance() : destination_;
      } else {
        return destinationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Destination uniquely identifies the instances of a service
     * to which the request/connection should be forwarded to.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setDestination(io.ourea.adapter.model.istio.Destination value) {
      if (destinationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        destination_ = value;
        onChanged();
      } else {
        destinationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Destination uniquely identifies the instances of a service
     * to which the request/connection should be forwarded to.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setDestination(
        io.ourea.adapter.model.istio.Destination.Builder builderForValue) {
      if (destinationBuilder_ == null) {
        destination_ = builderForValue.build();
        onChanged();
      } else {
        destinationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Destination uniquely identifies the instances of a service
     * to which the request/connection should be forwarded to.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeDestination(io.ourea.adapter.model.istio.Destination value) {
      if (destinationBuilder_ == null) {
        if (destination_ != null) {
          destination_ =
            io.ourea.adapter.model.istio.Destination.newBuilder(destination_).mergeFrom(value).buildPartial();
        } else {
          destination_ = value;
        }
        onChanged();
      } else {
        destinationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Destination uniquely identifies the instances of a service
     * to which the request/connection should be forwarded to.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearDestination() {
      if (destinationBuilder_ == null) {
        destination_ = null;
        onChanged();
      } else {
        destination_ = null;
        destinationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Destination uniquely identifies the instances of a service
     * to which the request/connection should be forwarded to.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.ourea.adapter.model.istio.Destination.Builder getDestinationBuilder() {
      
      onChanged();
      return getDestinationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Destination uniquely identifies the instances of a service
     * to which the request/connection should be forwarded to.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.ourea.adapter.model.istio.DestinationOrBuilder getDestinationOrBuilder() {
      if (destinationBuilder_ != null) {
        return destinationBuilder_.getMessageOrBuilder();
      } else {
        return destination_ == null ?
            io.ourea.adapter.model.istio.Destination.getDefaultInstance() : destination_;
      }
    }
    /**
     * <pre>
     * Destination uniquely identifies the instances of a service
     * to which the request/connection should be forwarded to.
     * </pre>
     *
     * <code>.istio.networking.v1alpha3.Destination destination = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ourea.adapter.model.istio.Destination, io.ourea.adapter.model.istio.Destination.Builder, io.ourea.adapter.model.istio.DestinationOrBuilder> 
        getDestinationFieldBuilder() {
      if (destinationBuilder_ == null) {
        destinationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ourea.adapter.model.istio.Destination, io.ourea.adapter.model.istio.Destination.Builder, io.ourea.adapter.model.istio.DestinationOrBuilder>(
                getDestination(),
                getParentForChildren(),
                isClean());
        destination_ = null;
      }
      return destinationBuilder_;
    }

    private int weight_ ;
    /**
     * <pre>
     * The proportion of traffic to be forwarded to the service
     * version. If there is only one destination in a rule, all traffic will be
     * routed to it irrespective of the weight.
     * </pre>
     *
     * <code>int32 weight = 2;</code>
     * @return The weight.
     */
    @java.lang.Override
    public int getWeight() {
      return weight_;
    }
    /**
     * <pre>
     * The proportion of traffic to be forwarded to the service
     * version. If there is only one destination in a rule, all traffic will be
     * routed to it irrespective of the weight.
     * </pre>
     *
     * <code>int32 weight = 2;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(int value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The proportion of traffic to be forwarded to the service
     * version. If there is only one destination in a rule, all traffic will be
     * routed to it irrespective of the weight.
     * </pre>
     *
     * <code>int32 weight = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      
      weight_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:istio.networking.v1alpha3.RouteDestination)
  }

  // @@protoc_insertion_point(class_scope:istio.networking.v1alpha3.RouteDestination)
  private static final io.ourea.adapter.model.istio.RouteDestination DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ourea.adapter.model.istio.RouteDestination();
  }

  public static io.ourea.adapter.model.istio.RouteDestination getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RouteDestination>
      PARSER = new com.google.protobuf.AbstractParser<RouteDestination>() {
    @java.lang.Override
    public RouteDestination parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RouteDestination(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RouteDestination> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RouteDestination> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ourea.adapter.model.istio.RouteDestination getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

