// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sidecar.proto

package io.ourea.adapter.model.istio;

public interface SidecarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:istio.networking.v1alpha3.Sidecar)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Criteria used to select the specific set of pods/VMs on which this
   * `Sidecar` configuration should be applied. If omitted, the `Sidecar`
   * configuration will be applied to all workload instances in the same namespace.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.WorkloadSelector workload_selector = 1;</code>
   * @return Whether the workloadSelector field is set.
   */
  boolean hasWorkloadSelector();
  /**
   * <pre>
   * Criteria used to select the specific set of pods/VMs on which this
   * `Sidecar` configuration should be applied. If omitted, the `Sidecar`
   * configuration will be applied to all workload instances in the same namespace.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.WorkloadSelector workload_selector = 1;</code>
   * @return The workloadSelector.
   */
  io.ourea.adapter.model.istio.WorkloadSelector getWorkloadSelector();
  /**
   * <pre>
   * Criteria used to select the specific set of pods/VMs on which this
   * `Sidecar` configuration should be applied. If omitted, the `Sidecar`
   * configuration will be applied to all workload instances in the same namespace.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.WorkloadSelector workload_selector = 1;</code>
   */
  io.ourea.adapter.model.istio.WorkloadSelectorOrBuilder getWorkloadSelectorOrBuilder();

  /**
   * <pre>
   * Ingress specifies the configuration of the sidecar for processing
   * inbound traffic to the attached workload instance. If omitted, Istio will
   * automatically configure the sidecar based on the information about the workload
   * obtained from the orchestration platform (e.g., exposed ports, services,
   * etc.). If specified, inbound ports are configured if and only if the
   * workload instance is associated with a service.
   * </pre>
   *
   * <code>repeated .istio.networking.v1alpha3.IstioIngressListener ingress = 2;</code>
   */
  java.util.List<io.ourea.adapter.model.istio.IstioIngressListener> 
      getIngressList();
  /**
   * <pre>
   * Ingress specifies the configuration of the sidecar for processing
   * inbound traffic to the attached workload instance. If omitted, Istio will
   * automatically configure the sidecar based on the information about the workload
   * obtained from the orchestration platform (e.g., exposed ports, services,
   * etc.). If specified, inbound ports are configured if and only if the
   * workload instance is associated with a service.
   * </pre>
   *
   * <code>repeated .istio.networking.v1alpha3.IstioIngressListener ingress = 2;</code>
   */
  io.ourea.adapter.model.istio.IstioIngressListener getIngress(int index);
  /**
   * <pre>
   * Ingress specifies the configuration of the sidecar for processing
   * inbound traffic to the attached workload instance. If omitted, Istio will
   * automatically configure the sidecar based on the information about the workload
   * obtained from the orchestration platform (e.g., exposed ports, services,
   * etc.). If specified, inbound ports are configured if and only if the
   * workload instance is associated with a service.
   * </pre>
   *
   * <code>repeated .istio.networking.v1alpha3.IstioIngressListener ingress = 2;</code>
   */
  int getIngressCount();
  /**
   * <pre>
   * Ingress specifies the configuration of the sidecar for processing
   * inbound traffic to the attached workload instance. If omitted, Istio will
   * automatically configure the sidecar based on the information about the workload
   * obtained from the orchestration platform (e.g., exposed ports, services,
   * etc.). If specified, inbound ports are configured if and only if the
   * workload instance is associated with a service.
   * </pre>
   *
   * <code>repeated .istio.networking.v1alpha3.IstioIngressListener ingress = 2;</code>
   */
  java.util.List<? extends io.ourea.adapter.model.istio.IstioIngressListenerOrBuilder> 
      getIngressOrBuilderList();
  /**
   * <pre>
   * Ingress specifies the configuration of the sidecar for processing
   * inbound traffic to the attached workload instance. If omitted, Istio will
   * automatically configure the sidecar based on the information about the workload
   * obtained from the orchestration platform (e.g., exposed ports, services,
   * etc.). If specified, inbound ports are configured if and only if the
   * workload instance is associated with a service.
   * </pre>
   *
   * <code>repeated .istio.networking.v1alpha3.IstioIngressListener ingress = 2;</code>
   */
  io.ourea.adapter.model.istio.IstioIngressListenerOrBuilder getIngressOrBuilder(
      int index);

  /**
   * <pre>
   * Egress specifies the configuration of the sidecar for processing
   * outbound traffic from the attached workload instance to other
   * services in the mesh. If not specified, inherits the system
   * detected defaults from the namespace-wide or the global default Sidecar.
   * </pre>
   *
   * <code>repeated .istio.networking.v1alpha3.IstioEgressListener egress = 3;</code>
   */
  java.util.List<io.ourea.adapter.model.istio.IstioEgressListener> 
      getEgressList();
  /**
   * <pre>
   * Egress specifies the configuration of the sidecar for processing
   * outbound traffic from the attached workload instance to other
   * services in the mesh. If not specified, inherits the system
   * detected defaults from the namespace-wide or the global default Sidecar.
   * </pre>
   *
   * <code>repeated .istio.networking.v1alpha3.IstioEgressListener egress = 3;</code>
   */
  io.ourea.adapter.model.istio.IstioEgressListener getEgress(int index);
  /**
   * <pre>
   * Egress specifies the configuration of the sidecar for processing
   * outbound traffic from the attached workload instance to other
   * services in the mesh. If not specified, inherits the system
   * detected defaults from the namespace-wide or the global default Sidecar.
   * </pre>
   *
   * <code>repeated .istio.networking.v1alpha3.IstioEgressListener egress = 3;</code>
   */
  int getEgressCount();
  /**
   * <pre>
   * Egress specifies the configuration of the sidecar for processing
   * outbound traffic from the attached workload instance to other
   * services in the mesh. If not specified, inherits the system
   * detected defaults from the namespace-wide or the global default Sidecar.
   * </pre>
   *
   * <code>repeated .istio.networking.v1alpha3.IstioEgressListener egress = 3;</code>
   */
  java.util.List<? extends io.ourea.adapter.model.istio.IstioEgressListenerOrBuilder> 
      getEgressOrBuilderList();
  /**
   * <pre>
   * Egress specifies the configuration of the sidecar for processing
   * outbound traffic from the attached workload instance to other
   * services in the mesh. If not specified, inherits the system
   * detected defaults from the namespace-wide or the global default Sidecar.
   * </pre>
   *
   * <code>repeated .istio.networking.v1alpha3.IstioEgressListener egress = 3;</code>
   */
  io.ourea.adapter.model.istio.IstioEgressListenerOrBuilder getEgressOrBuilder(
      int index);

  /**
   * <pre>
   * Configuration for the outbound traffic policy.  If your
   * application uses one or more external services that are not known
   * apriori, setting the policy to `ALLOW_ANY` will cause the
   * sidecars to route any unknown traffic originating from the
   * application to its requested destination. If not specified,
   * inherits the system detected defaults from the namespace-wide or
   * the global default Sidecar.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.OutboundTrafficPolicy outbound_traffic_policy = 4;</code>
   * @return Whether the outboundTrafficPolicy field is set.
   */
  boolean hasOutboundTrafficPolicy();
  /**
   * <pre>
   * Configuration for the outbound traffic policy.  If your
   * application uses one or more external services that are not known
   * apriori, setting the policy to `ALLOW_ANY` will cause the
   * sidecars to route any unknown traffic originating from the
   * application to its requested destination. If not specified,
   * inherits the system detected defaults from the namespace-wide or
   * the global default Sidecar.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.OutboundTrafficPolicy outbound_traffic_policy = 4;</code>
   * @return The outboundTrafficPolicy.
   */
  io.ourea.adapter.model.istio.OutboundTrafficPolicy getOutboundTrafficPolicy();
  /**
   * <pre>
   * Configuration for the outbound traffic policy.  If your
   * application uses one or more external services that are not known
   * apriori, setting the policy to `ALLOW_ANY` will cause the
   * sidecars to route any unknown traffic originating from the
   * application to its requested destination. If not specified,
   * inherits the system detected defaults from the namespace-wide or
   * the global default Sidecar.
   * </pre>
   *
   * <code>.istio.networking.v1alpha3.OutboundTrafficPolicy outbound_traffic_policy = 4;</code>
   */
  io.ourea.adapter.model.istio.OutboundTrafficPolicyOrBuilder getOutboundTrafficPolicyOrBuilder();
}
