// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sidecar.proto

package io.ourea.adapter.model.istio;

public interface WorkloadSelectorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:istio.networking.v1alpha3.WorkloadSelector)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * One or more labels that indicate a specific set of pods/VMs
   * on which the configuration should be applied. The scope of
   * label search is restricted to the configuration namespace in which the
   * the resource is present.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  int getLabelsCount();
  /**
   * <pre>
   * One or more labels that indicate a specific set of pods/VMs
   * on which the configuration should be applied. The scope of
   * label search is restricted to the configuration namespace in which the
   * the resource is present.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  boolean containsLabels(
      java.lang.String key);
  /**
   * Use {@link #getLabelsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getLabels();
  /**
   * <pre>
   * One or more labels that indicate a specific set of pods/VMs
   * on which the configuration should be applied. The scope of
   * label search is restricted to the configuration namespace in which the
   * the resource is present.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getLabelsMap();
  /**
   * <pre>
   * One or more labels that indicate a specific set of pods/VMs
   * on which the configuration should be applied. The scope of
   * label search is restricted to the configuration namespace in which the
   * the resource is present.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */

  java.lang.String getLabelsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * One or more labels that indicate a specific set of pods/VMs
   * on which the configuration should be applied. The scope of
   * label search is restricted to the configuration namespace in which the
   * the resource is present.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */

  java.lang.String getLabelsOrThrow(
      java.lang.String key);
}
